### ISSUE TITLE
Configure MegaLinter

### ISSUE THREAD

**Issue by omusavi** [benchpress-team/benchpress#1]
# Description
[Megalinter](https://megalinter.github.io/) is a single tool for us to manage all of our linting rules and run them in one place.

This story tracks local configuration of MegaLinter configuration and NOT integrating it with CI/CD ( #11 tracks this)

When configuring the MegaLinter, consider the following:
- Exclude existing files/paths
- Exclude linters we feel are noisy/not helpful
- Configure linters with "sane" rules 
  - Example: Markdown linting line length should be either set to a longer length (120)
 
 
# Acceptance Criteria
1. MegaLinter configuration checked into repository
2. Linter specific configuration checked in
3. Documentation added to CONTRIBUTING.md file describing [how to run locally](https://oxsecurity.github.io/megalinter/latest/mega-linter-runner/)

**Comment by omusavi** [comment]
Assign to robert

**Comment by Rhernandez513** [comment]
I see MegaLinter has many MD linting options, the first one shows MarkdownLint (although there is no mention of a default).  If MarkdownLint is indeed the default, MD doesn't need a manual config for line length, see the default config if no `.markdownlint.json` is provided: https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.markdownlint.json

**Comment by Rhernandez513** [comment]
Disabled `REPOSITORY_DEVSKIM` for now as it's a potentially known issue that it doesn't skip `node_modules`.  I did configure `node_modules` to be skipped, see: https://github.com/oxsecurity/megalinter/issues/1634

**Comment by Rhernandez513** [comment]
`dotnet-format` looks like it mostly provides options for running certain components at a time or enabling verbose logging, implying defaults settings should be used most of the time, see: https://github.com/dotnet/format

**Comment by Rhernandez513** [comment]
Full list of which linters have indv configs and notes for any that do not:

+----SUMMARY------+--------------------------+---------------+-------+-------+--------+--------------+

| Descriptor      | Linter                   | Mode          | Files | Fixed | Errors | Elapsed time |

+-----------------+--------------------------+---------------+-------+-------+--------+--------------+

| ✅ ACTION       | actionlint               | list_of_files |     1 |       |      0 |        0.17s | -> configged

| ❌ ARM          | arm-ttk                  | file          |     3 |       |      3 |        24.3s | -> configged

| ✅ BICEP        | bicep_linter             | file          |     3 |       |      0 |       22.08s | -> N/A

| ❌ COPYPASTE    | jscpd                    | project       |   n/a |       |      7 |        5.66s | ->configged

| ✅ CSHARP       | dotnet-format            | file          |    22 |     8 |      0 |      122.93s | ->config file format not found

| ✅ DOCKERFILE   | hadolint                 | list_of_files |     1 |       |      0 |        0.23s | -> configged

| ❌ EDITORCONFIG | editorconfig-checker     | list_of_files |    67 |       |      1 |         0.6s | -> configged

| ✅ JSON         | eslint-plugin-jsonc      | list_of_files |     9 |     1 |      0 |        7.12s | -> configged

| ✅ JSON         | jsonlint                 | list_of_files |     9 |       |      0 |        0.48s | -> configged

| ✅ JSON         | prettier                 | list_of_files |     9 |     1 |      0 |         5.2s | -> configged

| ✅ JSON         | v8r                      | list_of_files |     9 |       |      0 |       14.13s | -> config N/A

| ◬ MARKDOWN      | markdownlint             | list_of_files |     5 |     5 |      2 |        1.98s | -> configged

| ❌ MARKDOWN     | markdown-link-check      | list_of_files |     5 |       |      2 |       32.89s | . -configged

| ✅ MARKDOWN     | markdown-table-formatter | list_of_files |     5 |     5 |      0 |        1.39s | -> N/A

| ❌ POWERSHELL   | powershell               | file          |    11 |       |      9 |        25.6s | -> configged

| ✅ PYTHON       | bandit                   | list_of_files |     1 |       |      0 |        1.63s | -> configged

| ✅ PYTHON       | black                    | list_of_files |     1 |     0 |      0 |        1.44s | -> configged

| ✅ PYTHON       | flake8                   | list_of_files |     1 |       |      0 |        0.92s | -> configged

| ✅ PYTHON       | isort                    | list_of_files |     1 |     0 |      0 |         0.7s | -> configged

| ✅ PYTHON       | mypy                     | list_of_files |     1 |       |      0 |        8.56s | -> configged

| ✅ PYTHON       | pylint                   | list_of_files |     1 |       |      0 |        2.34s | -> configgged

| ✅ PYTHON       | pyright                  | list_of_files |     1 |       |      0 |       21.49s | -> configged

| ❌ REPOSITORY   | checkov                  | project       |   n/a |       |      7 |        54.1s | -> configged

| ◬ REPOSITORY    | devskim                  | project       |   n/a |       |      1 |         1.5s | -> Does not expose a config file

| ✅ REPOSITORY   | dustilock                | project       |   n/a |       |      0 |        0.45s | -> N/A

| ✅ REPOSITORY   | gitleaks                 | project       |   n/a |       |      0 |        1.44s | -> gitleaks

| ❌ REPOSITORY   | git_diff                 | project       |   n/a |       |      1 |        0.21s | -> N/A

| ✅ REPOSITORY   | secretlint               | project       |   n/a |       |      0 |        2.94s | -> configged

| ✅ REPOSITORY   | syft                     | project       |   n/a |       |      0 |        2.34s | -> configged

| ❌ REPOSITORY   | trivy                    | project       |   n/a |       |      1 |         7.0s | ->  megalinter does not expose a CONFIG_FILE var in the docs thorugh trivvy exposes a CLI:  -c, --config string      config path (default "trivy.yaml"), PR against megalinter?

| ❌ SPELL        | cspell                   | list_of_files |    67 |       |    281 |        6.59s | -> configged

| ✅ SPELL        | misspell                 | list_of_files |    67 |    15 |      0 |         1.8s | -> N/A

| ✅ YAML         | prettier                 | list_of_files |     2 |     1 |      0 |        3.02s | -> configged

| ✅ YAML         | v8r                      | list_of_files |     2 |       |      0 |        9.04s | -> Notes

| ✅ YAML         | yamllint                 | list_of_files |     2 |       |      0 |        0.47s | -> configged

+-----------------+--------------------------+---------------+-------+-------+--------+--------------+
